[package]
name = "sd-prisma"
version = "0.1.0"
edition = "2021"

[dependencies]
prisma-client-rust = { workspace = true }
serde = "1.0"
serde_json = "1.0"
sd-sync = { path = "../sync" }
sd-cache = { path = "../cache" }
